-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.4
--C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n pif_rom -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type bram -wp 00 -rp 1100 -addr_width 9 -data_width 32 -num_rows 512 -outdata REGISTERED -cascade -1 -resetmode SYNC -sync_reset -memfile e:/programming/vhdl/lattice/machxo2_breakout/pif_test/pifrom_pal.mem -memformat hex 

-- Wed Jun 28 19:30:53 2017

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity pif_rom is
    port (
        Address: in  std_logic_vector(8 downto 0); 
        OutClock: in  std_logic; 
        OutClockEn: in  std_logic; 
        Reset: in  std_logic; 
        Q: out  std_logic_vector(31 downto 0));
end pif_rom;

architecture Structure of pif_rom is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component DP8KC
        generic (INIT_DATA : in String; INITVAL_1F : in String; 
                INITVAL_1E : in String; INITVAL_1D : in String; 
                INITVAL_1C : in String; INITVAL_1B : in String; 
                INITVAL_1A : in String; INITVAL_19 : in String; 
                INITVAL_18 : in String; INITVAL_17 : in String; 
                INITVAL_16 : in String; INITVAL_15 : in String; 
                INITVAL_14 : in String; INITVAL_13 : in String; 
                INITVAL_12 : in String; INITVAL_11 : in String; 
                INITVAL_10 : in String; INITVAL_0F : in String; 
                INITVAL_0E : in String; INITVAL_0D : in String; 
                INITVAL_0C : in String; INITVAL_0B : in String; 
                INITVAL_0A : in String; INITVAL_09 : in String; 
                INITVAL_08 : in String; INITVAL_07 : in String; 
                INITVAL_06 : in String; INITVAL_05 : in String; 
                INITVAL_04 : in String; INITVAL_03 : in String; 
                INITVAL_02 : in String; INITVAL_01 : in String; 
                INITVAL_00 : in String; ASYNC_RESET_RELEASE : in String; 
                RESETMODE : in String; GSR : in String; 
                WRITEMODE_B : in String; WRITEMODE_A : in String; 
                CSDECODE_B : in String; CSDECODE_A : in String; 
                REGMODE_B : in String; REGMODE_A : in String; 
                DATA_WIDTH_B : in Integer; DATA_WIDTH_A : in Integer);
        port (DIA8: in  std_logic; DIA7: in  std_logic; 
            DIA6: in  std_logic; DIA5: in  std_logic; 
            DIA4: in  std_logic; DIA3: in  std_logic; 
            DIA2: in  std_logic; DIA1: in  std_logic; 
            DIA0: in  std_logic; ADA12: in  std_logic; 
            ADA11: in  std_logic; ADA10: in  std_logic; 
            ADA9: in  std_logic; ADA8: in  std_logic; 
            ADA7: in  std_logic; ADA6: in  std_logic; 
            ADA5: in  std_logic; ADA4: in  std_logic; 
            ADA3: in  std_logic; ADA2: in  std_logic; 
            ADA1: in  std_logic; ADA0: in  std_logic; CEA: in  std_logic; 
            OCEA: in  std_logic; CLKA: in  std_logic; WEA: in  std_logic; 
            CSA2: in  std_logic; CSA1: in  std_logic; 
            CSA0: in  std_logic; RSTA: in  std_logic; 
            DIB8: in  std_logic; DIB7: in  std_logic; 
            DIB6: in  std_logic; DIB5: in  std_logic; 
            DIB4: in  std_logic; DIB3: in  std_logic; 
            DIB2: in  std_logic; DIB1: in  std_logic; 
            DIB0: in  std_logic; ADB12: in  std_logic; 
            ADB11: in  std_logic; ADB10: in  std_logic; 
            ADB9: in  std_logic; ADB8: in  std_logic; 
            ADB7: in  std_logic; ADB6: in  std_logic; 
            ADB5: in  std_logic; ADB4: in  std_logic; 
            ADB3: in  std_logic; ADB2: in  std_logic; 
            ADB1: in  std_logic; ADB0: in  std_logic; CEB: in  std_logic; 
            OCEB: in  std_logic; CLKB: in  std_logic; WEB: in  std_logic; 
            CSB2: in  std_logic; CSB1: in  std_logic; 
            CSB0: in  std_logic; RSTB: in  std_logic; 
            DOA8: out  std_logic; DOA7: out  std_logic; 
            DOA6: out  std_logic; DOA5: out  std_logic; 
            DOA4: out  std_logic; DOA3: out  std_logic; 
            DOA2: out  std_logic; DOA1: out  std_logic; 
            DOA0: out  std_logic; DOB8: out  std_logic; 
            DOB7: out  std_logic; DOB6: out  std_logic; 
            DOB5: out  std_logic; DOB4: out  std_logic; 
            DOB3: out  std_logic; DOB2: out  std_logic; 
            DOB1: out  std_logic; DOB0: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute MEM_LPC_FILE of pif_rom_0_0_1 : label is "pif_rom.lpc";
    attribute MEM_INIT_FILE of pif_rom_0_0_1 : label is "pifrom_pal.mem";
    attribute MEM_LPC_FILE of pif_rom_0_1_0 : label is "pif_rom.lpc";
    attribute MEM_INIT_FILE of pif_rom_0_1_0 : label is "pifrom_pal.mem";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    pif_rom_0_0_1: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000003E00000000000000000000003FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF", 
        INITVAL_1E=> "0x3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF0000000180301D2000D2", 
        INITVAL_1D=> "0x0FE80100D2241001017F200001FE7F1FE80000D20FE80100D214080100001A47F100801A40000000", 
        INITVAL_1C=> "0x00000000D20FE80100D2306102407F2FE033BE000018007900070802288010010301802008000180", 
        INITVAL_1B=> "0x2008000100000181FE80001801FE80200181FE1400080000342000020100030FF028001000004980", 
        INITVAL_1A=> "0x001002002000100030FF02800100000C9802000020838260240512C2008000180301803000010180", 
        INITVAL_19=> "0x089800007F0406420000300101FE1802900200101FE18028002013035828101E03419C3C83C07180", 
        INITVAL_18=> "0x100181FE10129B036950200181FE1400100030FF02194349AC3500F030FF0280020080102181FE00", 
        INITVAL_17=> "0x028002C0640414806838219800178031830301800010C348A8001800018420180030FF00094300BC", 
        INITVAL_16=> "0x0C0641A8300690C201003002C20100000181FE14000800002400800030FF000C410064200B600018", 
        INITVAL_15=> "0x1FF803181400180028FF0309020180302800005030058088000FFFF0FE7F0FF00081003000C20000", 
        INITVAL_14=> "0x101003000010100301801FE0000008101800180C00008200003008020014300001FE00100801A400", 
        INITVAL_13=> "0x02000088361FE7F101800FE8010018100D21A47F30080300D2100003018000F80000A2000A2000A1", 
        INITVAL_12=> "0x00000000D2100000000000000000000A4001A47F100801A4A0000802008000056200593A78000180", 
        INITVAL_11=> "0x3004E0BDD8000DF0FE00106031BE8F001881A5D21FEFF3000010083001881BE5F3A4520FE0000052", 
        INITVAL_10=> "0x000D2000D2000D2000D2000D2002001A4000A47F000000A4001A4000A47F000000A4C01E4801609A", 
        INITVAL_0F=> "0x00000000000000027E00000000000000000000003FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF", 
        INITVAL_0E=> "0x3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF00000010400000007880", 
        INITVAL_0D=> "0x3FA020308004A40021FA1003C3FFFF3FE10078803FA020308004A340403C101FD004181000000000", 
        INITVAL_0C=> "0x00000060803FA020308038025049FF3FFF03800001000024000201904C081C025078340602C05024", 
        INITVAL_0B=> "0x0401C0306C0E025216680C8043A2010E025226250E07000C260E07000C6C04B1E04A6C0D8060426C", 
        INITVAL_0A=> "0x0D806002420046804B2C04A680D006042680C8050562104A060082303E64000700D8680C80102074", 
        INITVAL_09=> "0x04A741497304226140A41282629E2504A9C140212AA2504AA8158210422513806008250460400C1F", 
        INITVAL_08=> "0x150252CE2504A060082303E252DE25158B004B7404A2500806046C204B7C04AB0128393E02530694", 
        INITVAL_07=> "0x04A88042060082500806046881848C04C211088C00A2604221100840102B1208C04BA01202510821", 
        INITVAL_06=> "0x0080604A06008231081F130211309800825366251308000E210568004BBC00B650F8260F0070F825", 
        INITVAL_05=> "0x38A74042250F07404BCC04A23008043DE01000250402504A003E1FB3F9F83E81004C741682500018", 
        INITVAL_04=> "0x0382004828058300683C24000010250601C04A250042305828050FF05825038023A0000264000001", 
        INITVAL_03=> "0x024192CA073F9FB008043F8000802500000021FC0400C0181001807002403800C041020380203002", 
        INITVAL_02=> "0x028FF00010000200061C01E18028FF0C03C101FD0041810025000011FE10078421FE020000600401", 
        INITVAL_01=> "0x002C210400049C03F880381FC381F001000000003F9FC00804001201A800381C0000043FA0402004", 
        INITVAL_00=> "0x00850000500204004840018403FE100C003009FD00218008100080A009FD00210008000C60600000", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "SYNC", 
        REGMODE_B=> "OUTREG", REGMODE_A=> "OUTREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  9)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>scuba_vlo, 
            DIA2=>scuba_vlo, DIA1=>scuba_vlo, DIA0=>scuba_vlo, 
            ADA12=>scuba_vlo, ADA11=>Address(8), ADA10=>Address(7), 
            ADA9=>Address(6), ADA8=>Address(5), ADA7=>Address(4), 
            ADA6=>Address(3), ADA5=>Address(2), ADA4=>Address(1), 
            ADA3=>Address(0), ADA2=>scuba_vlo, ADA1=>scuba_vlo, 
            ADA0=>scuba_vlo, CEA=>OutClockEn, OCEA=>OutClockEn, 
            CLKA=>OutClock, WEA=>scuba_vlo, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>scuba_vlo, RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>scuba_vhi, ADB11=>Address(8), ADB10=>Address(7), 
            ADB9=>Address(6), ADB8=>Address(5), ADB7=>Address(4), 
            ADB6=>Address(3), ADB5=>Address(2), ADB4=>Address(1), 
            ADB3=>Address(0), ADB2=>scuba_vlo, ADB1=>scuba_vlo, 
            ADB0=>scuba_vlo, CEB=>OutClockEn, OCEB=>OutClockEn, 
            CLKB=>OutClock, WEB=>scuba_vlo, CSB2=>scuba_vlo, 
            CSB1=>scuba_vlo, CSB0=>scuba_vlo, RSTB=>Reset, DOA8=>Q(8), 
            DOA7=>Q(7), DOA6=>Q(6), DOA5=>Q(5), DOA4=>Q(4), DOA3=>Q(3), 
            DOA2=>Q(2), DOA1=>Q(1), DOA0=>Q(0), DOB8=>Q(17), DOB7=>Q(16), 
            DOB6=>Q(15), DOB5=>Q(14), DOB4=>Q(13), DOB3=>Q(12), 
            DOB2=>Q(11), DOB1=>Q(10), DOB0=>Q(9));

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    pif_rom_0_1_0: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x000000000000000000000000000000000000000003E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F", 
        INITVAL_1E=> "0x03E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F03E1F00000000040080702A07", 
        INITVAL_1D=> "0x0140602207000040080A00C110080A0080402A070140602207000150081100E0A00C1100E0000000", 
        INITVAL_1C=> "0x0000002A070140602207008000000600E1100E000001500015000000000000800022110221102211", 
        INITVAL_1B=> "0x02211022110220000011022040040402A000000002215004000221101415000000001102A0200011", 
        INITVAL_1A=> "0x0220A00C0000C15000000001102A020001102A0200000000000000000C110221502A1502A0400804", 
        INITVAL_19=> "0x0001102A020000002A1102200000000001502200000000001502A000000002200000000000000006", 
        INITVAL_18=> "0x0220000000000000000000C00000000221500000000000000000000000000001102A020080000011", 
        INITVAL_17=> "0x00015000000000000000000110001500000022150040000000022110140002A11000000220002A00", 
        INITVAL_16=> "0x0000000000000000220602A00022150040000000022150040000011000000080602A0002A0702200", 
        INITVAL_15=> "0x0001500000022110000000000008110080402200008000001102A0202A1502A04000040080002215", 
        INITVAL_14=> "0x02A1502A1502A1502A15008000000000811000000040002211008000080002A02008000000400E04", 
        INITVAL_13=> "0x0000000C0702A020080400811008000080700E0A00C04022070080200C040081102A0002A0002A00", 
        INITVAL_12=> "0x02A060080702215008150081502A0400E1500E0A00C1100E000080600C040220000C0000E0600406", 
        INITVAL_11=> "0x00C000000702207014060081100E060000400E0702A0200804022040080400E0700E070140602207", 
        INITVAL_10=> "0x02A0702A0702A0702A0702A070081500E0400E0A00C1100E1500E0400E0A00C1100E0800C0701007", 
        INITVAL_0F=> "0x00000000000000000000000000000000000000003FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF", 
        INITVAL_0E=> "0x3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF3FFFF000000B05A2B5022B502", 
        INITVAL_0D=> "0x2904A2950208502004020855A09548094022B5022904A29502085592055A205480954A2040000000", 
        INITVAL_0C=> "0x000002B3022904A295022B422084212055A204001F13B00133000210C7043DE103DFED3DBED3DBEC", 
        INITVAL_0B=> "0x3D9EC3D9EB3D688209E93D39C31B8C3D088208803D3EB000543D5E9349E811104101E93D4000B9EA", 
        INITVAL_0A=> "0x3D3441080610DE811104101E93DC000F9EB3D6081066B094140B8B8101EB339E83D1E83D10520BEC", 
        INITVAL_09=> "0x001E83D40019C7C3D1EE3D67420888131E83D66C20888131EB3D05A092C23D61C19873170A412898", 
        INITVAL_08=> "0x3D488208100C694148BC10888208A83D3E8111040204A038541700411104121E93D08820088209E9", 
        INITVAL_07=> "0x195EE0F8140386B0281C171EB00BE80C05C3D5E80004A080843D5EA010803D1E8111043D2C63D675", 
        INITVAL_06=> "0x0281C0C614038B83D6A03D4543D5E800088208803D3EA01012149EA11104303293DCC43D1013DC88", 
        INITVAL_05=> "0x209E8020803D3E8101041107C36BB42078C3688020A280012C2291022914229100E3E83D000257EC", 
        INITVAL_04=> "0x3D9EC3D9ED3DBED3DBEF3DE001F0183DFEF04010220713D7E93D3043D2303DF283DE002092920321", 
        INITVAL_03=> "0x00052285022D5400D65A0855A0D6022D703207780F76B2D7032D6780F65A0056B2C4022C4022C402", 
        INITVAL_02=> "0x2C44A2C7032B56220562205622C5022076A205480954A2044220AAD16B022D40208402205BD1309C", 
        INITVAL_01=> "0x17A02005022D503280422D76A207EF0B15A20F022B5632B5632C56B2C75A20703205022804228502", 
        INITVAL_00=> "0x21100211002110021100215002050A2010220540085422050A201022044008542204222950204502", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "SYNC", 
        REGMODE_B=> "OUTREG", REGMODE_A=> "OUTREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  9)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>scuba_vlo, 
            DIA2=>scuba_vlo, DIA1=>scuba_vlo, DIA0=>scuba_vlo, 
            ADA12=>scuba_vlo, ADA11=>Address(8), ADA10=>Address(7), 
            ADA9=>Address(6), ADA8=>Address(5), ADA7=>Address(4), 
            ADA6=>Address(3), ADA5=>Address(2), ADA4=>Address(1), 
            ADA3=>Address(0), ADA2=>scuba_vlo, ADA1=>scuba_vlo, 
            ADA0=>scuba_vlo, CEA=>OutClockEn, OCEA=>OutClockEn, 
            CLKA=>OutClock, WEA=>scuba_vlo, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>scuba_vlo, RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>scuba_vhi, ADB11=>Address(8), ADB10=>Address(7), 
            ADB9=>Address(6), ADB8=>Address(5), ADB7=>Address(4), 
            ADB6=>Address(3), ADB5=>Address(2), ADB4=>Address(1), 
            ADB3=>Address(0), ADB2=>scuba_vlo, ADB1=>scuba_vlo, 
            ADB0=>scuba_vlo, CEB=>OutClockEn, OCEB=>OutClockEn, 
            CLKB=>OutClock, WEB=>scuba_vlo, CSB2=>scuba_vlo, 
            CSB1=>scuba_vlo, CSB0=>scuba_vlo, RSTB=>Reset, DOA8=>Q(26), 
            DOA7=>Q(25), DOA6=>Q(24), DOA5=>Q(23), DOA4=>Q(22), 
            DOA3=>Q(21), DOA2=>Q(20), DOA1=>Q(19), DOA0=>Q(18), 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>Q(31), 
            DOB3=>Q(30), DOB2=>Q(29), DOB1=>Q(28), DOB0=>Q(27));

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of pif_rom is
    for Structure
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:DP8KC use entity MACHXO2.DP8KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
