-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.4
-- Wed Jun 28 19:30:53 2017

-- parameterized module component declaration
component pif_rom
    port (Address: in  std_logic_vector(8 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : pif_rom
    port map (Address(8 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(31 downto 0)=>__);
